package com.xsis.android.batch217.utils

/*=================================================*/
/*                  KONSTANTA DATABASE             */
/*=================================================*/
val TABEL_AGAMA ="agama"
val ID_AGAMA="id_agama"
val NAMA_AGAMA="nama_agama"
val DES_AGAMA="des_agama"

val TABEL_BACKOFFICE_POSITION ="backoffice_position"
val ID_BACKOFFICE="id_backoffice"
val NAMA_BACKOFFICE="nama_backoffice"
val LEVEL_BACKOFFICE="level_backoffice"
val NOTE_BACKOFFICE="note_backoffice"

val TABEL_COMPANY ="company"
val ID_COMPANY="id_company"
val NAMA_COMPANY="nama_company"
val KOTA_COMPANY="kota_company"
val KDPOS_COMPANY="kdpos_company"
val JLN_COMPANY="jln_company"
val BUILDING_COMPANY="building_company"
val FLOOR_COMPANY="floor_company"

val TABEL_KELUARGA_DATA = "keluarga_data"
val ID_JENIS = "id_jenis"
val JENIS_KELUARGA = "jenis_keluarga"
val TABEL_KELUARGA_DETAIL = "keluarga_detail"
val ID_ANGGOTA = "id_anggota"
val NAMA_ANGGOTA = "nama_anggota"

val TABEL_POSITION_LEVEL ="position_level"
val ID_POSITION="id_position"
val NAMA_POSITION="nama_position"
val DES_POSITION="des_position"

val TABEL_CONTRACT_STATUS = "contract_status"
val ID_CONTRACT="id_contract"
val NAMA_CONTRACT = "nama_contract"
val DES_CONTRACT = "des_contract"

val TABEL_EMPLOYEE_STATUS="employee_status"
val ID_EMP="id_emp"
val NAMA_EMP = "nama_emp"
val DES_EMP = "des_emp"

val TABEL_EMPLOYEE_TYPE = "employee_type"
val ID_EMP_TYPE = "id_emp_type"
val NAMA_EMP_TYPE = "nama_emp_type"
val DES_EMP_TYPE= "des_emp_type"

val TABEL_GRADE= "grade"
val ID_GRADE="id_grade"
val NAMA_GRADE="nama_grade"
val DES_GRADE="des_grade"

val TABEL_CATATAN = "jenis_catatan"
val ID_CATATAN= "id_catatan"
val NAMA_CATATAN ="nama_catatan"
val DES_CATATAN = "des_catatan"

val TABEL_KEAHLIAN= "keahlian"
val ID_KEAHLIAN = "id_keahlian"
val NAMA_KEAHLIAN= "nama_keahlian"
val DES_KEAHLIAN="des_keahlian"

val TABEL_PENDIDIKAN= "pendidikan"
val ID_PENDIDIKAN = "id_pendidikan"
val NAMA_PENDIDIKAN= "nama_pendidikan"
val DES_PENDIDIKAN= "des_pendidikan"

val TABEL_PERIODE="periode"
val ID_PERIODE="id_periode"
val NAMA_PERIODE="nama_periode"
val DES_PERIODE="des_periode"

val TABEL_PRF="prf_status"
val ID_PRF="id_prf"
val NAMA_PRF="nama_prf"
val DES_PRF="des_prf"

val TABEL_PROVIDER = "provider_tools"
val ID_PROVIDER="id_provider"
val NAMA_PROVIDER="nama_provider"
val DES_PROVIDER="des_provider"

val TABEL_STATUS_NIKAH="status_pernikahan"
val ID_STATUS_NIKAH="id_status"
val NAMA_STATUS_NIKAH="nama_status"
val DES_STATUS_NIKAH="des_status"

val TABEL_TIPE_IDENTITAS ="tipe_identitas"
val ID_IDENTITAS="id_identitas"
val NAMA_IDENTITAS="nama_identitas"
val DES_IDENTITAS="des_identitas"

val TABEL_TIPE_TES="tipe_tes"
val ID_TES="id_tes"
val NAMA_TES="nama_tes"
val DES_TES="des_tes"

val TABEL_TRAINING= "training"
val ID_TRAINING="id_training"
val CODE_TRAINING="code_training"
val NAMA_TRAINING="nama_training"

val TABEL_TRAINING_ORG="training_organizer"
val ID_TRAINING_ORG="id_to"
val NAMA_TRAINING_ORG="nama_to"
val DES_TRAINING_ORG="des_to"

val TABEL_EMPLOYEE_TRAINING ="employee_training"
val ID_EMPLOYEE_TRAINING="id_employee_training"
val NAMA_TRAINEE = "nama_trainee"
val NAMA_EMPLOYEE_TRAINING="nama_employee_training"
val NAMA_EMPLOYEE_TRAINING_ORG="nama_employee_to"
val DATE_EMPLOYEE_TRAINING="date_employee_training"
val TYPE_EMPLOYEE_TRAINING="type_employee_training"
val TYPE_EMPLOYEE_CERTIFICATION="type_employee_certification"

val TABEL_NAMA_TRAINING ="nama_training"
val ID_NAMA_TRAINING ="id_nama_training"
val NAMA_NYA_TRAINING ="nama_nya_training"

val TABEL_NAMA_TRAINING_ORGANIZER ="nama_training_organizer"
val ID_NAMA_TRAINING_ORGANIZER ="id_nama_training_organizer"
val NAMA_NYA_TRAINING_ORGANIZER ="nama_nya_training_organizer"

val TABEL_TRAINING_TYPE ="training_type"
val ID_TRAINING_TYPE ="id_training_type"
val NAMA_TRAINING_TYPE ="nama_training_type"

val TABEL_CERTIFICATION_TYPE ="certification_type"
val ID_CERTIFICATION_TYPE ="id_certification_type"
val NAMA_CERTIFICATION_TYPE ="nama_certification_type"

val TABEL_PRF_REQUEST = "prf_request"
val ID_PRF_REQUEST = "id_prf_request"
val TANGGAL = "tanggal"
val TYPE = "type"
val PLACEMENT = "placement"
val PID = "pid"
val LOCATION = "location"
val PERIOD = "period"
val USER_NAME = "user_name"
val TELP_NUMBER = "telp_number"
val EMAIL = "email"
val NOTEBOOK = "notebook"
val OVERTIME = "overtime"
val BAST = "bast"
val BILLING = "billing"

val TABEL_PRF_CANDIDATE = "prf_candidates"
val ID_FROM_PRF = "id_from_prf"
val ID_PRF_CANDIDATE = "id_prf_candidate"
val NAMA_PRF_CANDIDATE = "nama_prf_candidate"
val BATCH = "batch"
val POSITION = "position"
val PLACEMENT_DATE = "placement_date"
val SRF_NUMBER = "srf_number"
val ALLOWENCE_CANDIDATE = "allowence_candidate"
val STATUS_CANDIDATE = "status_candidate"
val SIGN_CONTRACT_DATE = "sign_contract_date"
val NOTES = "notes"

val TABEL_TIMESHEET = "timesheet"
val ID_TIMESHEET = "id_timesheet"
val STATUS_TIMESHEET = "status_timesheet"
val CLIENT_DATABASE = "client_timesheet"
val REPORT_DATE_TIMESHEET = "report_date_timesheet"
val START_REPORT_DATE_TIMESHEET = "start_report_date_timesheet"
val END_REPORT_DATE_TIMESHEET ="end_report_date_timesheet"
val OVERTIME_TIMESHEET ="overtime_timesheet"
val START_REPORT_OVERTIME = "start_overtime_timesheet"
val END_REPORT_OVERTIME ="end_overtime_timesheet"
val NOTES_TIMESHEET ="notes_timesheet"
val PROGRESS_TIMESHEET ="progress_timesheet"

val TABEL_STATUS_TIMESHEET = "status_timesheet"
val ID_STSTIMESHEET = "id_ststimesheet"
val NAMA_STSTIMESHEET = "nama_timesheet"


val TABEL_PROJECT = "project"
val ID_PROJECT = "id_project"
val KODE_COMPANY_PROJECT = "kode_comp_project"
val LOCATION_PROJECT = "location_project"
val DEPARTMENT_PROJECT = "department_project"
val USER_PROJECT = "user_project"
val NAME_PROJECT = "name_project"
val START_PROJECT = "start_project"
val END_PROJECT ="end_project"
val ROLE_PROJECT ="role_project"
val PHASE_PROJECT = "phase_project"
val DES_PROJECT ="des_project"
val TECH_PROJECT ="tech_project"
val TASK_PROJECT ="task_project"

val TABEL_PROJECT_CREATE = "project_create"
val ID_PROJECT_CREATE = "id_project_create"
val PID_CREATE = "pid"
val NO_PO_SPK_KONTRAK = "no_po_spk_kontrak"
val CLIENT = "client"
val START_DATE_PROJECT_CREATE = "start_date"
val END_DATE_PROJECT_CREATE = "end_date"
val POSISI_DI_CLIENT = "posisi_di_client"
val JENIS_OVERTIME = "jenis_overtime"
val CATATAN_FIX_RATE = "catatan_fix_rate"
val tanggal_BAST = "tanggal_bast"


val TABEL_LEAVE_REQUEST = "leave_request"
val ID_LEAVE= "id_leave_request"
val START = "start"
val END = "end"
val ADDRESS = "address"
val CONTACT = "contact"
val REASON = "reason"
val APPROVAL1= ""
val APPROVAL2 = ""
val APPROVAL3 =""

val TABEL_LEAVE_TYPE="leave_type"
val ID_LEAVE_TYPE = "id_leave_type"
val LEAVE_TYPE="leave_type"
val QUOTA ="quota"

val TABEL_CUTI_KHUSUS="cuti_khusus"
val ID_CUTI_KHUSUS= "id_cuti_khusus"
val LEAVE_NAME= "leave_name"

val TABEL_TYPE_PRF = "type_prf"
val ID_TYPE_PRF = "id_type_prf"
val NAMA_TYPE_PRF = "nama_type_prf"
val DESKRIPSI_TYPE_PRF = "deskripsi_type_prf"

val TABEL_EMPLOYEE_POSITION = "employee_position"
val ID_EMPLOYEE_POSITION = "id_employee_position"
val DESKRIPSI_POSITION = "deskripsi_position"


//nama field sama
val IS_DELETED= "is_deleted"
/*=================================================*/